### PR TITLE
Format timestamp

### LINKED ISSUE #20: [BUG]- timestamp on client side needs to be typed as number instead of string
**Describe the bug**
The timestamp state on the client side needs to be type number instead of string so we can run any math as needed.

### LINKED ISSUE #21: Show the timestamp in HH:MM:SS
## What
Convert the timestamp from seconds to HH:MM:SS

## How
Create a reusable function that converts seconds into HH:MM:SS.

Cases:
1.  00:00
2. 00:05
3. 00:59
4. 25:59
5. 02:59:59
6. 9999:59:59

## Testing
- Write jest tests to verify the timestamps

### PR DESCRIPTION
**Pull request by intelagense**
Adds a helper function that is used to format time displayed as `HH:MM:SS` in both the room display and in the title bar.

notes: Does not work above 99 hours.
There are no jest tests yet. Waiting on tests from nmpereira/time-share-v2#5

### CODE REVIEW

File: src/components/Room.tsx [hunk 1]
```diff
@@ -47,7 +52,8 @@ function Room() {
   useEffect(() => {
     console.log("timestamp", timestamp);
     // update the document title, with roomName and timestamp
-    document.title = `${timestamp}-${window.location.href.split("/")[3]}`;
+    const formattedTimestamp = formatTimestamp(timestamp);
+    document.title = `${formattedTimestamp}-${window.location.href.split("/")[3]}`;
```
Comment (nmpereira) [inline src/components/Room.tsx]: Instead of adding 2 lines you can just combine it into a single line
```suggestion
    document.title = `${formatTimestamp(timestamp)}-${window.location.href.split("/")[3]}`;
```

File: src/components/Events.tsx [hunk 2]
```diff
@@ -1,8 +1,11 @@
-export function Events({ events }: { events: string }) {
+import formatTimestamp from '../helpers/formatTimestamp';
+
+export function Events({ events }: { events: number }) {
   console.log("events", events);
+  console.log(formatTimestamp(events));
```
Comment (nmpereira) [inline src/components/Events.tsx]: Remove the console logs on line 4 and line 5
```suggestion

```

File: src/components/Room.tsx [hunk 3]
```diff
@@ -24,8 +27,10 @@ function Room() {
 
     function onTimerUpdate(value: string) {
       console.log("timer", value);
-      setTimestamp(value);
+      const timer = parseInt(value);
+      setTimestamp(timer);
```
Comment (nmpereira) [inline src/components/Room.tsx]: This can probably be a single line
```suggestion
      setTimestamp(parseInt(value));
```

**Review by nmpereira — CHANGES_REQUESTED** [review]

**Review by nmpereira — APPROVED** [review]
